### ISSUE TITLE
Return correct content type

### ISSUE THREAD

**Issue by johnjohndoe** [refugeehackathon/refugeetransit-api#3]
The JSON response from the **API** does **not** return the correct content type:
### Example:

```
$ curl -i https://migrationapi.tem.li/api/en/pois                    
HTTP/1.1 200 OK
Date: Mon, 26 Oct 2015 17:48:01 GMT
Server: Apache
Vary: Accept-Encoding
Strict-Transport-Security: max-age=15768000;includeSubdomains
X-Frame-Options: sameorigin
Transfer-Encoding: chunked
Content-Type: text/html;charset=UTF-8
```

It should be `Content-Type: application/json;charset=utf-8` instead.

**Comment by jelhan** [comment]
Should set HTTP response header content type: http://docs.slimframework.com/response/headers/

There is also an alias method on Slim object, which isn't documented: `$app->contentType('application/json');` https://github.com/slimphp/Slim/blob/faf83069298593bdfd8482a14bda171937473fc1/Slim/Slim.php#L1060-L1067

**Comment by mischazip** [comment]
I am going to fix it today afternoon. Thank you!

**Comment by mischazip** [comment]
Fixed. Please copy the new index.php to the server.

**Comment by t2d** [comment]
done

**Comment by johnjohndoe** [comment]
:+1:
